function h = draw_undefined(ax, x, y, color)
% DESSINE UN ÉLÉMENT TYPE "Undefined"
% carré contour noir avec un "?" au centre

    hold(ax, 'on');

    % Taille du carré
    s = 0.4;

    % === 1. Carré vide (contour noir) ===
    rect = rectangle(ax, ...
        'Position', [x - s/2, y - s/2, s, s], ...
        'FaceColor', 'none', ...
        'EdgeColor', color, ...
        'LineWidth', 1.5);

    % === 2. Symbole "?" noir au centre ===
    txt = text(ax, x, y, '?', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'Color', color, ...
        'FontWeight', 'bold', ...
        'FontSize', 12, ...
        'HitTest', 'off');  % pour que le clic passe au carré

    % === 3. Groupe graphique unique ===
    h = hggroup(ax);
    set([rect txt], 'Parent', h);
end