function h = draw_classelement(ax, x, y, color)
% DESSINE UN ÉLÉMENT GRAPHIQUE TYPE "classelement"
% carré rouge avec un E majuscule noir au centre

    hold(ax, 'on');

    % Taille du carré
    s = 0.4;

    % === 1. Création du carré rouge ===
    rect = rectangle(ax, ...
        'Position', [x - s/2, y - s/2, s, s], ...
        'FaceColor', color, ...
        'EdgeColor', 'k', ...
        'LineWidth', 1.2);

    % === 2. Texte "E" noir au centre ===
    txt = text(ax, x, y, 'E', ...
        'HorizontalAlignment', 'center', ...
        'VerticalAlignment', 'middle', ...
        'Color', 'k', ...
        'FontWeight', 'bold', ...
        'FontSize', 12, ...
        'HitTest', 'off');  % pour que le clic passe au carré

    % === 3. Groupe graphique unique ===
    h = hggroup(ax);
    set([rect txt], 'Parent', h);
end