function [X, F, t] = run_ga(problem, x0, popSize, opts)

opts = optimoptions(opts, ...
    'InitialPopulationMatrix', x0, ...
    'PopulationSize', popSize);

tic;
[X, F] = gamultiobj(problem.objective, problem.nVars, ...
                    [], [], [], [], ...
                    problem.lb, problem.ub, ...
                    problem.nonlcon, problem.intcon, opts);
t = toc;
end