function out = model
%
% test.m
%
% Model exported on Mar 4 2025, 16:38 by COMSOL 6.2.0.415.

import com.comsol.model.*
import com.comsol.model.util.*

model = ModelUtil.create('Model');

model.modelPath(['E:\OneDrive - ETS\CRIAQ-REAR\Maitrise LB\Mod' native2unicode(hex2dec({'00' 'e9'}), 'unicode') 'lisation num' native2unicode(hex2dec({'00' 'e9'}), 'unicode') 'rique']);

model.param.set('d12', '20e-3', 'distance inter-microphone');
model.param.set('d2s', '80e-3', 'distance microphone 2 - solution');
model.param.set('xl1', '0', ['ligne d''acotement ' native2unicode(hex2dec({'00' 'e0'}), 'unicode') ' gauche de la solution courante']);

model.variable.create('var1');
model.variable('var1').set('co', '348.9679', 'Vitesse du son');
model.variable('var1').set('cp', '0.24263', 'Capacite thermique a pression constante');
model.variable('var1').set('kappa', '6.1686e-06', 'Conductivite thermique');
model.variable('var1').set('neta', '1.8496e-05', 'Viscosite dynamique');
model.variable('var1').set('rho0', '1.2414', 'Masse volumique de l''air');
model.variable('var1').set('gamma', '1.4003', 'Masse volumique de l''air');

model.component.create('component', true);

model.component('component').geom.create('geometry', 2);

model.component('component').material.create('air_perso', 'Common');
model.component('component').material('air_perso').label('Air');
model.component('component').material('air_perso').set('family', 'air');
model.component('component').material('air_perso').materialType('nonSolid');
model.component('component').material('air_perso').propertyGroup('def').set('thermalexpansioncoefficient', '');
model.component('component').material('air_perso').propertyGroup('def').set('molarmass', '');
model.component('component').material('air_perso').propertyGroup('def').set('bulkviscosity', '');
model.component('component').material('air_perso').propertyGroup('def').set('thermalexpansioncoefficient', {'alpha_p(pA,T)' '0' '0' '0' 'alpha_p(pA,T)' '0' '0' '0' 'alpha_p(pA,T)'});
model.component('component').material('air_perso').propertyGroup('def').set('molarmass', '0.02897[kg/mol]');
model.component('component').material('air_perso').propertyGroup('def').set('bulkviscosity', 'muB(T)');
model.component('component').material('air_perso').propertyGroup('def').set('relpermeability', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('component').material('air_perso').propertyGroup('def').set('relpermittivity', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('component').material('air_perso').propertyGroup('def').set('dynamicviscosity', 'eta(T)');
model.component('component').material('air_perso').propertyGroup('def').set('ratioofspecificheat', '1.4');
model.component('component').material('air_perso').propertyGroup('def').set('electricconductivity', {'0[S/m]' '0' '0' '0' '0[S/m]' '0' '0' '0' '0[S/m]'});
model.component('component').material('air_perso').propertyGroup('def').set('heatcapacity', 'Cp(T)');
model.component('component').material('air_perso').propertyGroup('def').set('density', 'rho(pA,T)');
model.component('component').material('air_perso').propertyGroup('def').set('thermalconductivity', {'k(T)' '0' '0' '0' 'k(T)' '0' '0' '0' 'k(T)'});
model.component('component').material('air_perso').propertyGroup('def').set('soundspeed', 'cs(T)');
model.component('component').material('air_perso').propertyGroup('def').addInput('temperature');
model.component('component').material('air_perso').propertyGroup('def').addInput('pressure');
model.component('component').material('air_perso').propertyGroup('def').func.create('eta', 'Piecewise');
model.component('component').material('air_perso').propertyGroup('def').func('eta').set('arg', 'T');
model.component('component').material('air_perso').propertyGroup('def').func('eta').set('pieces', {'200.0' '1600.0' '-8.38278E-7+8.35717342E-8*T^1-7.69429583E-11*T^2+4.6437266E-14*T^3-1.06585607E-17*T^4'});
model.component('component').material('air_perso').propertyGroup('def').func('eta').set('argunit', 'K');
model.component('component').material('air_perso').propertyGroup('def').func('eta').set('fununit', 'Pa*s');
model.component('component').material('air_perso').propertyGroup('def').func.create('Cp', 'Piecewise');
model.component('component').material('air_perso').propertyGroup('def').func('Cp').set('arg', 'T');
model.component('component').material('air_perso').propertyGroup('def').func('Cp').set('pieces', {'200.0' '1600.0' '1047.63657-0.372589265*T^1+9.45304214E-4*T^2-6.02409443E-7*T^3+1.2858961E-10*T^4'});
model.component('component').material('air_perso').propertyGroup('def').func('Cp').set('argunit', 'K');
model.component('component').material('air_perso').propertyGroup('def').func('Cp').set('fununit', 'J/(kg*K)');
model.component('component').material('air_perso').propertyGroup('def').func.create('rho', 'Analytic');
model.component('component').material('air_perso').propertyGroup('def').func('rho').set('expr', 'pA*0.02897/R_const[K*mol/J]/T');
model.component('component').material('air_perso').propertyGroup('def').func('rho').set('args', {'pA' 'T'});
model.component('component').material('air_perso').propertyGroup('def').func('rho').set('fununit', 'kg/m^3');
model.component('component').material('air_perso').propertyGroup('def').func('rho').set('argunit', {'Pa' 'K'});
model.component('component').material('air_perso').propertyGroup('def').func('rho').set('plotargs', {'pA' '101325' '101325'; 'T' '273.15' '293.15'});
model.component('component').material('air_perso').propertyGroup('def').func.create('k', 'Piecewise');
model.component('component').material('air_perso').propertyGroup('def').func('k').set('arg', 'T');
model.component('component').material('air_perso').propertyGroup('def').func('k').set('pieces', {'200.0' '1600.0' '-0.00227583562+1.15480022E-4*T^1-7.90252856E-8*T^2+4.11702505E-11*T^3-7.43864331E-15*T^4'});
model.component('component').material('air_perso').propertyGroup('def').func('k').set('argunit', 'K');
model.component('component').material('air_perso').propertyGroup('def').func('k').set('fununit', 'W/(m*K)');
model.component('component').material('air_perso').propertyGroup('def').func.create('cs', 'Analytic');
model.component('component').material('air_perso').propertyGroup('def').func('cs').set('expr', 'sqrt(1.4*R_const[K*mol/J]/0.02897*T)');
model.component('component').material('air_perso').propertyGroup('def').func('cs').set('args', 'T');
model.component('component').material('air_perso').propertyGroup('def').func('cs').set('fununit', 'm/s');
model.component('component').material('air_perso').propertyGroup('def').func('cs').set('argunit', 'K');
model.component('component').material('air_perso').propertyGroup('def').func('cs').set('plotargs', {'T' '273.15' '373.15'});
model.component('component').material('air_perso').propertyGroup('def').func.create('an1', 'Analytic');
model.component('component').material('air_perso').propertyGroup('def').func('an1').set('funcname', 'alpha_p');
model.component('component').material('air_perso').propertyGroup('def').func('an1').set('expr', '-1/rho(pA,T)*d(rho(pA,T),T)');
model.component('component').material('air_perso').propertyGroup('def').func('an1').set('args', {'pA' 'T'});
model.component('component').material('air_perso').propertyGroup('def').func('an1').set('fununit', '1/K');
model.component('component').material('air_perso').propertyGroup('def').func('an1').set('argunit', {'Pa' 'K'});
model.component('component').material('air_perso').propertyGroup('def').func('an1').set('plotargs', {'pA' '101325' '101325'; 'T' '273.15' '373.15'});
model.component('component').material('air_perso').propertyGroup('def').func.create('an2', 'Analytic');
model.component('component').material('air_perso').propertyGroup('def').func('an2').set('funcname', 'muB');
model.component('component').material('air_perso').propertyGroup('def').func('an2').set('expr', '0.6*eta(T)');
model.component('component').material('air_perso').propertyGroup('def').func('an2').set('args', 'T');
model.component('component').material('air_perso').propertyGroup('def').func('an2').set('fununit', 'Pa*s');
model.component('component').material('air_perso').propertyGroup('def').func('an2').set('argunit', 'K');
model.component('component').material('air_perso').propertyGroup('def').func('an2').set('plotargs', {'T' '200' '1600'});
model.component('component').material('air_perso').propertyGroup.create('RefractiveIndex', 'Refractive index');
model.component('component').material('air_perso').propertyGroup('RefractiveIndex').set('n', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('component').material('air_perso').propertyGroup.create('NonlinearModel', 'Nonlinear model');
model.component('component').material('air_perso').propertyGroup('NonlinearModel').set('BA', '(def.gamma+1)/2');
model.component('component').material('air_perso').propertyGroup.create('idealGas', 'Ideal gas');
model.component('component').material('air_perso').propertyGroup('idealGas').func.create('Cp', 'Piecewise');
model.component('component').material('air_perso').propertyGroup('idealGas').func('Cp').label('Piecewise 2');
model.component('component').material('air_perso').propertyGroup('idealGas').func('Cp').set('arg', 'T');
model.component('component').material('air_perso').propertyGroup('idealGas').func('Cp').set('pieces', {'200.0' '1600.0' '1047.63657-0.372589265*T^1+9.45304214E-4*T^2-6.02409443E-7*T^3+1.2858961E-10*T^4'});
model.component('component').material('air_perso').propertyGroup('idealGas').func('Cp').set('argunit', 'K');
model.component('component').material('air_perso').propertyGroup('idealGas').func('Cp').set('fununit', 'J/(kg*K)');
model.component('component').material('air_perso').propertyGroup('idealGas').set('Rs', 'R_const/Mn');
model.component('component').material('air_perso').propertyGroup('idealGas').set('heatcapacity', 'Cp(T)');
model.component('component').material('air_perso').propertyGroup('idealGas').set('ratioofspecificheat', '1.4');
model.component('component').material('air_perso').propertyGroup('idealGas').set('molarmass', '0.02897');
model.component('component').material('air_perso').propertyGroup('idealGas').addInput('temperature');
model.component('component').material('air_perso').propertyGroup('idealGas').addInput('pressure');
model.component('component').material('air_perso').propertyGroup('def').set('thermalexpansioncoefficient', '');
model.component('component').material('air_perso').propertyGroup('def').set('molarmass', '');
model.component('component').material('air_perso').propertyGroup('def').set('bulkviscosity', '');
model.component('component').material('air_perso').propertyGroup('def').set('thermalexpansioncoefficient', {'alpha_p(pA,T)' '0' '0' '0' 'alpha_p(pA,T)' '0' '0' '0' 'alpha_p(pA,T)'});
model.component('component').material('air_perso').propertyGroup('def').set('molarmass', '0.02897[kg/mol]');
model.component('component').material('air_perso').propertyGroup('def').set('bulkviscosity', 'muB(T)');
model.component('component').material('air_perso').propertyGroup('def').set('relpermeability', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('component').material('air_perso').propertyGroup('def').set('relpermittivity', {'1' '0' '0' '0' '1' '0' '0' '0' '1'});
model.component('component').material('air_perso').propertyGroup('def').set('dynamicviscosity', 'eta(T)');
model.component('component').material('air_perso').propertyGroup('def').set('ratioofspecificheat', '1.4');
model.component('component').material('air_perso').propertyGroup('def').set('electricconductivity', {'0[S/m]' '0' '0' '0' '0[S/m]' '0' '0' '0' '0[S/m]'});
model.component('component').material('air_perso').propertyGroup('def').set('heatcapacity', 'Cp(T)');
model.component('component').material('air_perso').propertyGroup('def').set('density', 'rho(pA,T)');
model.component('component').material('air_perso').propertyGroup('def').set('thermalconductivity', {'k(T)' '0' '0' '0' 'k(T)' '0' '0' '0' 'k(T)'});
model.component('component').material('air_perso').propertyGroup('def').set('soundspeed', 'cs(T)');
model.component('component').material('air_perso').propertyGroup('def').addInput('temperature');
model.component('component').material('air_perso').propertyGroup('def').addInput('pressure');

model.component('component').physics.create('phy_ap', 'PressureAcoustics', 'geometry');
model.component('component').physics('phy_ap').selection.set([]);
model.component('component').physics.create('phy_tv', 'ThermoacousticsSinglePhysics', 'geometry');
model.component('component').physics('phy_tv').selection.set([]);

model.component('component').multiphysics.create('multiphy_bnd', 'AcousticThermoacousticBoundary', 1);
model.component('component').multiphysics('multiphy_bnd').selection.set([]);

model.component('component').mesh.create('mesh');

model.param.set('w1', '0.03[m]', 'largeur');
model.param.set('xc1', 'xl1+w1/2', 'ligne centrale');
model.param.set('xr1', 'xl1+w1', ['ligne d''acotement ' native2unicode(hex2dec({'00' 'e0'}), 'unicode') ' droite']);
model.param.set('xl2', 'xl1+w1+2[mm]', ['ligne d''acotement ' native2unicode(hex2dec({'00' 'e0'}), 'unicode') ' gauche']);
model.param.set('sol1_l', '0.001', [native2unicode(hex2dec({'00' 'e9'}), 'unicode') 'paisseur des plaques']);
model.param.set('sol1_d', '0.001', ['incr' native2unicode(hex2dec({'00' 'e9'}), 'unicode') 'ment']);
model.param.set('sol1_m', '0.005', ['espace avant 1' native2unicode(hex2dec({'00' 'e8'}), 'unicode') 're plaque ' native2unicode(hex2dec({'00' 'e0'}), 'unicode') ' gauche']);
model.param.set('sol1_n', '0.0074', ['espace avant 1' native2unicode(hex2dec({'00' 'e8'}), 'unicode') 're plaque ' native2unicode(hex2dec({'00' 'e0'}), 'unicode') ' droite']);
model.param.set('sol1_a1', '0.008', ['longueur de la 1' native2unicode(hex2dec({'00' 'e8'}), 'unicode') 're plaque gauche']);
model.param.set('sol1_b1', '0.008', ['longueur de la 1' native2unicode(hex2dec({'00' 'e8'}), 'unicode') 're plaque droite']);
model.param.set('nu', '1.81e-05[Pa*s]');
model.param.set('rho', '1.2 [kg/m^3]');
model.param.set('omega0', '2*pi*3000');
model.param.set('d_visc', 'sqrt(2*nu/(omega0*rho))');

model.component('component').geom('geometry').create('sol1_frc', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_frc').set('pos', {'xl1' '-sol1_m'});
model.component('component').geom('geometry').feature('sol1_frc').set('size', {'w1' 'sol1_m'});
model.component('component').geom('geometry').create('sol1_lp1', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lp1').set('pos', {'xl1+sol1_a1+0*sol1_d' '-1*(sol1_m+sol1_l)'});
model.component('component').geom('geometry').feature('sol1_lp1').set('size', {'w1-(sol1_a1+0*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_lc1', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lc1').set('pos', {'xl1' '-0*(sol1_m+sol1_l)-sol1_n'});
model.component('component').geom('geometry').feature('sol1_lc1').set('size', {'w1' 'sol1_n-sol1_m-sol1_l'});
model.component('component').geom('geometry').create('sol1_rp1', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rp1').set('pos', {'xl1' '-0*(sol1_m+sol1_l)-sol1_n-sol1_l'});
model.component('component').geom('geometry').feature('sol1_rp1').set('size', {'w1-(sol1_b1+0*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_rc1', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rc1').set('pos', {'xl1' '-2*(sol1_m+sol1_l)+sol1_l'});
model.component('component').geom('geometry').feature('sol1_rc1').set('size', {'w1' '2*sol1_m-sol1_n'});
model.component('component').geom('geometry').create('sol1_lp2', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lp2').set('pos', {'xl1+sol1_a1+1*sol1_d' '-2*(sol1_m+sol1_l)'});
model.component('component').geom('geometry').feature('sol1_lp2').set('size', {'w1-(sol1_a1+1*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_lc2', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lc2').set('pos', {'xl1' '-1*(sol1_m+sol1_l)-sol1_n'});
model.component('component').geom('geometry').feature('sol1_lc2').set('size', {'w1' 'sol1_n-sol1_m-sol1_l'});
model.component('component').geom('geometry').create('sol1_rp2', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rp2').set('pos', {'xl1' '-1*(sol1_m+sol1_l)-sol1_n-sol1_l'});
model.component('component').geom('geometry').feature('sol1_rp2').set('size', {'w1-(sol1_b1+1*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_rc2', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rc2').set('pos', {'xl1' '-3*(sol1_m+sol1_l)+sol1_l'});
model.component('component').geom('geometry').feature('sol1_rc2').set('size', {'w1' '2*sol1_m-sol1_n'});
model.component('component').geom('geometry').create('sol1_lp3', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lp3').set('pos', {'xl1+sol1_a1+2*sol1_d' '-3*(sol1_m+sol1_l)'});
model.component('component').geom('geometry').feature('sol1_lp3').set('size', {'w1-(sol1_a1+2*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_lc3', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lc3').set('pos', {'xl1' '-2*(sol1_m+sol1_l)-sol1_n'});
model.component('component').geom('geometry').feature('sol1_lc3').set('size', {'w1' 'sol1_n-sol1_m-sol1_l'});
model.component('component').geom('geometry').create('sol1_rp3', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rp3').set('pos', {'xl1' '-2*(sol1_m+sol1_l)-sol1_n-sol1_l'});
model.component('component').geom('geometry').feature('sol1_rp3').set('size', {'w1-(sol1_b1+2*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_rc3', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rc3').set('pos', {'xl1' '-4*(sol1_m+sol1_l)+sol1_l'});
model.component('component').geom('geometry').feature('sol1_rc3').set('size', {'w1' '2*sol1_m-sol1_n'});
model.component('component').geom('geometry').create('sol1_lp4', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lp4').set('pos', {'xl1+sol1_a1+3*sol1_d' '-4*(sol1_m+sol1_l)'});
model.component('component').geom('geometry').feature('sol1_lp4').set('size', {'w1-(sol1_a1+3*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_lc4', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lc4').set('pos', {'xl1' '-3*(sol1_m+sol1_l)-sol1_n'});
model.component('component').geom('geometry').feature('sol1_lc4').set('size', {'w1' 'sol1_n-sol1_m-sol1_l'});
model.component('component').geom('geometry').create('sol1_rp4', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rp4').set('pos', {'xl1' '-3*(sol1_m+sol1_l)-sol1_n-sol1_l'});
model.component('component').geom('geometry').feature('sol1_rp4').set('size', {'w1-(sol1_b1+3*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_rc4', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rc4').set('pos', {'xl1' '-5*(sol1_m+sol1_l)+sol1_l'});
model.component('component').geom('geometry').feature('sol1_rc4').set('size', {'w1' '2*sol1_m-sol1_n'});
model.component('component').geom('geometry').create('sol1_lp5', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lp5').set('pos', {'xl1+sol1_a1+4*sol1_d' '-5*(sol1_m+sol1_l)'});
model.component('component').geom('geometry').feature('sol1_lp5').set('size', {'w1-(sol1_a1+4*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_lc5', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lc5').set('pos', {'xl1' '-4*(sol1_m+sol1_l)-sol1_n'});
model.component('component').geom('geometry').feature('sol1_lc5').set('size', {'w1' 'sol1_n-sol1_m-sol1_l'});
model.component('component').geom('geometry').create('sol1_rp5', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rp5').set('pos', {'xl1' '-4*(sol1_m+sol1_l)-sol1_n-sol1_l'});
model.component('component').geom('geometry').feature('sol1_rp5').set('size', {'w1-(sol1_b1+4*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_rc5', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rc5').set('pos', {'xl1' '-6*(sol1_m+sol1_l)+sol1_l'});
model.component('component').geom('geometry').feature('sol1_rc5').set('size', {'w1' '2*sol1_m-sol1_n'});
model.component('component').geom('geometry').create('sol1_lp6', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lp6').set('pos', {'xl1+sol1_a1+5*sol1_d' '-6*(sol1_m+sol1_l)'});
model.component('component').geom('geometry').feature('sol1_lp6').set('size', {'w1-(sol1_a1+5*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_lc6', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lc6').set('pos', {'xl1' '-5*(sol1_m+sol1_l)-sol1_n'});
model.component('component').geom('geometry').feature('sol1_lc6').set('size', {'w1' 'sol1_n-sol1_m-sol1_l'});
model.component('component').geom('geometry').create('sol1_rp6', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rp6').set('pos', {'xl1' '-5*(sol1_m+sol1_l)-sol1_n-sol1_l'});
model.component('component').geom('geometry').feature('sol1_rp6').set('size', {'w1-(sol1_b1+5*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_rc6', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rc6').set('pos', {'xl1' '-7*(sol1_m+sol1_l)+sol1_l'});
model.component('component').geom('geometry').feature('sol1_rc6').set('size', {'w1' '2*sol1_m-sol1_n'});
model.component('component').geom('geometry').create('sol1_lp7', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lp7').set('pos', {'xl1+sol1_a1+6*sol1_d' '-7*(sol1_m+sol1_l)'});
model.component('component').geom('geometry').feature('sol1_lp7').set('size', {'w1-(sol1_a1+6*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_lc7', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lc7').set('pos', {'xl1' '-6*(sol1_m+sol1_l)-sol1_n'});
model.component('component').geom('geometry').feature('sol1_lc7').set('size', {'w1' 'sol1_n-sol1_m-sol1_l'});
model.component('component').geom('geometry').create('sol1_rp7', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rp7').set('pos', {'xl1' '-6*(sol1_m+sol1_l)-sol1_n-sol1_l'});
model.component('component').geom('geometry').feature('sol1_rp7').set('size', {'w1-(sol1_b1+6*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_rc7', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rc7').set('pos', {'xl1' '-8*(sol1_m+sol1_l)+sol1_l'});
model.component('component').geom('geometry').feature('sol1_rc7').set('size', {'w1' '2*sol1_m-sol1_n'});
model.component('component').geom('geometry').create('sol1_lp8', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lp8').set('pos', {'xl1+sol1_a1+7*sol1_d' '-8*(sol1_m+sol1_l)'});
model.component('component').geom('geometry').feature('sol1_lp8').set('size', {'w1-(sol1_a1+7*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_lc8', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lc8').set('pos', {'xl1' '-7*(sol1_m+sol1_l)-sol1_n'});
model.component('component').geom('geometry').feature('sol1_lc8').set('size', {'w1' 'sol1_n-sol1_m-sol1_l'});
model.component('component').geom('geometry').create('sol1_rp8', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rp8').set('pos', {'xl1' '-7*(sol1_m+sol1_l)-sol1_n-sol1_l'});
model.component('component').geom('geometry').feature('sol1_rp8').set('size', {'w1-(sol1_b1+7*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_rc8', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rc8').set('pos', {'xl1' '-9*(sol1_m+sol1_l)+sol1_l'});
model.component('component').geom('geometry').feature('sol1_rc8').set('size', {'w1' '2*sol1_m-sol1_n'});
model.component('component').geom('geometry').create('sol1_lp9', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lp9').set('pos', {'xl1+sol1_a1+8*sol1_d' '-9*(sol1_m+sol1_l)'});
model.component('component').geom('geometry').feature('sol1_lp9').set('size', {'w1-(sol1_a1+8*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_lc9', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_lc9').set('pos', {'xl1' '-8*(sol1_m+sol1_l)-sol1_n'});
model.component('component').geom('geometry').feature('sol1_lc9').set('size', {'w1' 'sol1_n-sol1_m-sol1_l'});
model.component('component').geom('geometry').create('sol1_rp9', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rp9').set('pos', {'xl1' '-8*(sol1_m+sol1_l)-sol1_n-sol1_l'});
model.component('component').geom('geometry').feature('sol1_rp9').set('size', {'w1-(sol1_b1+8*sol1_d)' 'sol1_l'});
model.component('component').geom('geometry').create('sol1_rc9', 'Rectangle');
model.component('component').geom('geometry').feature('sol1_rc9').set('pos', {'xl1' '-10*(sol1_m+sol1_l)+sol1_l'});
model.component('component').geom('geometry').feature('sol1_rc9').set('size', {'w1' '2*sol1_m-sol1_n'});
model.component('component').geom('geometry').run;
model.component('component').geom('geometry').create('sol1_union', 'Union');
model.component('component').geom('geometry').feature('sol1_union').selection('input').set({'sol1_frc' 'sol1_lp1' 'sol1_lc1' 'sol1_rp1' 'sol1_rc1' 'sol1_lp2' 'sol1_lc2' 'sol1_rp2' 'sol1_rc2' 'sol1_lp3'  ...
'sol1_lc3' 'sol1_rp3' 'sol1_rc3' 'sol1_lp4' 'sol1_lc4' 'sol1_rp4' 'sol1_rc4' 'sol1_lp5' 'sol1_lc5' 'sol1_rp5'  ...
'sol1_rc5' 'sol1_lp6' 'sol1_lc6' 'sol1_rp6' 'sol1_rc6' 'sol1_lp7' 'sol1_lc7' 'sol1_rp7' 'sol1_rc7' 'sol1_lp8'  ...
'sol1_lc8' 'sol1_rp8' 'sol1_rc8' 'sol1_lp9' 'sol1_lc9' 'sol1_rp9' 'sol1_rc9'});
model.component('component').geom('geometry').feature('sol1_union').set('intbnd', false);
model.component('component').geom('geometry').run;

model.component('component').selection.create('sol1', 'Box');
model.component('component').selection('sol1').set('entitydim', 2);
model.component('component').selection('sol1').set('ymax', '0.01[mm]');
model.component('component').selection('sol1').set('xmax', 'xr1+0.01[mm]');
model.component('component').selection('sol1').set('xmin', 'xl1-0.01[mm]');
model.component('component').selection('sol1').set('condition', 'inside');
model.component('component').selection.create('sol1_bnd_ap_tv', 'Box');
model.component('component').selection('sol1_bnd_ap_tv').set('entitydim', 1);
model.component('component').selection('sol1_bnd_ap_tv').set('ymax', '0.01[mm]');
model.component('component').selection('sol1_bnd_ap_tv').set('ymin', '-0.01[mm]');
model.component('component').selection('sol1_bnd_ap_tv').set('xmax', 'xr1+0.01[mm]');
model.component('component').selection('sol1_bnd_ap_tv').set('xmin', 'xl1-0.01[mm]');
model.component('component').selection('sol1_bnd_ap_tv').set('condition', 'inside');
model.component('component').selection.create('sol1_bnd_lyr_tv', 'Box');
model.component('component').selection('sol1_bnd_lyr_tv').set('entitydim', 1);
model.component('component').selection('sol1_bnd_lyr_tv').set('ymax', '-0.01[mm]');
model.component('component').selection('sol1_bnd_lyr_tv').set('xmax', 'xr1+0.01[mm]');
model.component('component').selection('sol1_bnd_lyr_tv').set('xmin', 'xl1-0.01[mm]');

model.component('component').physics('phy_tv').selection.set([1]);

model.component('component').mesh('mesh').create('sol1_ftri', 'FreeTri');
model.component('component').mesh('mesh').feature('sol1_ftri').selection.named('sol1');
model.component('component').mesh('mesh').feature('sol1_ftri').create('size1', 'Size');
model.component('component').mesh('mesh').feature('sol1_ftri').feature('size1').set('hauto', 1);
model.component('component').mesh('mesh').run;
model.component('component').mesh('mesh').create('sol1bl', 'BndLayer');
model.component('component').mesh('mesh').feature('sol1bl').selection.named('sol1');
model.component('component').mesh('mesh').feature('sol1bl').set('splitdivangle', 75);
model.component('component').mesh('mesh').feature('sol1bl').set('layerdec', 1);
model.component('component').mesh('mesh').feature('sol1bl').create('blp', 'BndLayerProp');
model.component('component').mesh('mesh').feature('sol1bl').feature('blp').selection.named('sol1_bnd_lyr_tv');
model.component('component').mesh('mesh').feature('sol1bl').feature('blp').set('blnlayers', 4);
model.component('component').mesh('mesh').feature('sol1bl').feature('blp').set('blstretch', 1.1);
model.component('component').mesh('mesh').feature('sol1bl').feature('blp').set('inittype', 'blhtot');
model.component('component').mesh('mesh').feature('sol1bl').feature('blp').set('blhmin', 'd_visc');
model.component('component').mesh('mesh').run;
model.component('component').mesh('mesh').data.transferMesh;

model.component('component').view('view1').camera.set('position', [-3 -4 3]);
model.component('component').view('view1').camera.set('up', [0 0 1]);

model.label('test.mph');

model.component('component').mesh('mesh').run('sol1_ftri');
model.component('component').mesh('mesh').feature('sol1bl').feature('blp').set('inittype', 'blhtot');
model.component('component').mesh('mesh').feature('sol1bl').feature('blp').set('blhtot', 'd_visc');
model.component('component').mesh('mesh').run;
model.component('component').mesh('mesh').feature('sol1bl').set('smoothtransition', false);
model.component('component').mesh('mesh').run('sol1bl');

out = model;
